name: create a release branch
on: [workflow_dispatch]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: hashicorp/actions-create-release-branch@v1
        with:
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
