on:
  workflow_call:
    inputs:
      derrick-binary:
        required: true
        type: string
      derrick-tar:
        required: true
        type: string
      derrick-image:
        required: true
        type: string
      derrick-odr-tar:
        required: true
        type: string
      derrick-odr-image:
        required: true
        type: string

jobs:
  publish-images:
    name: Publish Images
    runs-on: ubuntu-latest
    outputs:
      derrick-image: ${{ steps.push-derrick.outputs.derrick-image }}
      derrick-odr-image: ${{ steps.push-derrick-odr.outputs.derrick-odr-image }}
    steps:
      - name: Download Derrick Image
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.derrick-tar }}

      - name: Download Derrick ODR Image
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.derrick-odr-tar }}

      - name: GHCR Login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Tag and Push Derrick
        id: push-derrick
        env:
          GHCR_IMAGE_NAME: ghcr.io/nomatronio/derrick/alpha:${{ github.sha }}
        run: |
          docker load < ${{ inputs.derrick-tar }}
          docker tag ${{ inputs.derrick-image }} "${GHCR_IMAGE_NAME}"
          docker push "${GHCR_IMAGE_NAME}"
          echo "derrick-image=${{env.GHCR_IMAGE_NAME}}" | tee -a "$GITHUB_OUTPUT"

      - name: Tag and Push Derrick ODR
        id: push-derrick-odr
        env:
          GHCR_IMAGE_NAME: ghcr.io/nomatronio/derrick/alpha-odr:${{ github.sha }}
        run: |
          docker load < ${{ inputs.derrick-odr-tar }}
          docker tag ${{ inputs.derrick-odr-image }} "${GHCR_IMAGE_NAME}"
          docker push "${GHCR_IMAGE_NAME}"
          echo "derrick-odr-image=${{env.GHCR_IMAGE_NAME}}" | tee -a "$GITHUB_OUTPUT"

  run_tests:
    name: Run End-to-end tests
    runs-on: ubuntu-latest
    needs: publish-images
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0

      - uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.derrick-binary }}

      - name: Download Docker image tarballs
        uses: actions/download-artifact@v4
        with:
          pattern: derrick_*_${{ github.sha }}.docker.tar
          merge-multiple: true

      - name: Load Docker images for install and upgrade
        run: |
          docker load < "${{ inputs.derrick-tar }}"
          docker load < "${{ inputs.derrick-odr-tar }}"
          docker tag "${{ inputs.derrick-image }}" "${{ needs.publish-images.outputs.derrick-image }}"
          docker tag "${{ inputs.derrick-odr-image }}" "${{ needs.publish-images.outputs.derrick-odr-image }}"

      - name: install derrick binary
        id: install-derrick
        run: |
          unzip ${{ inputs.derrick-binary }}
          mkdir -p "$(pwd)/bin"
          mv derrick "$(pwd)/bin/derrick"
          echo "wp-binary=$(pwd)/bin/derrick" | tee -a "$GITHUB_OUTPUT"

      - name: Run Tests
        env: 
          E2E_PLATFORM: Docker
          DERRICK_BINARY: ${{ steps.install-derrick.outputs.wp-binary }}
          DERRICK_SERVERIMAGE: ${{ inputs.derrick-image }}
          DERRICK_ODRIMAGE: ${{ inputs.derrick-odr-image }}
          DERRICK_SERVERIMAGE_UPGRADE: ${{ needs.publish-images.outputs.derrick-image }}
          DERRICK_ODRIMAGE_UPGRADE: ${{ needs.publish-images.outputs.derrick-odr-image }}
        run: ./test-e2e/run-test.sh
